version: '3.8'

services:
  eureka:
    image: kurisuzhang/server
    container_name: eureka
    ports:
      - "8761:8761"

  gateway:
    image: kurisuzhang/gateway
    container_name: gateway
    ports:
      - "8080:8080"
    environment:
      - EUREKA_SERVER_URL=${EUREKA_SERVER_URL}
    depends_on:
      - eureka

  cart:
    image: kurisuzhang/cart
    container_name: cart
    ports:
      - "8081:8081"
    environment:
      - EUREKA_SERVER_URL=${EUREKA_SERVER_URL}
      - ZIPKIN_URL=${ZIPKIN_URL}
      - POSTGRESQL_URL=${POSTGRESQL_URL}
      - POSTGRESQL_USERNAME=${POSTGRESQL_USERNAME}
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
    depends_on:
      - eureka
      - postgres

  order:
    image: kurisuzhang/order
    container_name: order
    ports:
      - "8082:8082"
    environment:
      - EUREKA_SERVER_URL=${EUREKA_SERVER_URL}
      - ZIPKIN_URL=${ZIPKIN_URL}
      - POSTGRESQL_URL=${POSTGRESQL_URL}
      - POSTGRESQL_USERNAME=${POSTGRESQL_USERNAME}
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
    depends_on:
      - eureka
      - postgres

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"

  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRESQL_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRESQL_PASSWORD}
      - POSTGRES_DB=${POSTGRESQL_DATABASE}
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
